import {randomHierarchy, randomNode} from "jsplumbtoolkit-demo-support"
import {
    HierarchyLayout,
    ObjectInfo,
    Node,
    MiniviewPlugin,
    EndpointSpec,
    AnchorLocations,
    DEFAULT,
    BlankEndpoint,
    DotEndpoint,
    EVENT_TAP,
    EVENT_CLICK,
    EVENT_CANVAS_CLICK,
    ready,
    newInstance, StateMachineConnector
} from "@jsplumbtoolkit/browser-ui"
import {getExtras, getParams} from "./layout-params"
import {SUPPORTED_LAYOUTS} from "./layout-list"

ready(function () {

    const toolkit = newInstance({
        beforeStartDetach:() => { return false }
    })

    const view = {
        nodes: {
            [DEFAULT]: {
                templateId: "tmplNode"
            }
        },
        edges: {
            [DEFAULT]: {
                connector: { type:StateMachineConnector.type, options:{ curviness: 10 } },
                paintStyle: { strokeWidth: 2, stroke: '#89bcde' },
                endpoints: [ { type:DotEndpoint.type, options:{ radius: 4 } }, BlankEndpoint.type ] as [EndpointSpec, EndpointSpec]
            }
        }
    }

    const mainElement = document.querySelector("#jtk-demo-layouts"),
        canvasElement = mainElement.querySelector(".jtk-demo-canvas"),
        miniviewElement = mainElement.querySelector(".miniview"),
        layoutSelector = document.querySelector("#layout") as HTMLSelectElement,
        layoutOptionsSelector = document.querySelector("#layout-options") as HTMLSelectElement

    function populateOptions(layout:string) {
        layoutOptionsSelector.innerHTML = ''
        layoutOptionsSelector.setAttribute("data-layout", layout)

        const o = document.createElement("option")
        o.value = layout
        o.innerHTML = "Default"
        layoutOptionsSelector.appendChild(o)

        getExtras(layout).forEach( (extra:any) => {
            const o = document.createElement("option")
            o.value = layout
            o.setAttribute("extra", extra.id)
            o.innerHTML = extra.label
            layoutOptionsSelector.appendChild(o)
        })
        layoutOptionsSelector.selectedIndex = 0

    }

    // make a random hierarchy and store how many nodes there are; we will use this when we add new nodes.
    const hierarchy = randomHierarchy(3)

    toolkit.load({type: "json", data: hierarchy})

    const renderer = toolkit.render(canvasElement, {
        zoomToFit: true,
        view: view,
        layout: {
            type: HierarchyLayout.type
        },
        events: {
            [EVENT_CANVAS_CLICK] :(e:Event) => {
                toolkit.clearSelection()
            }
        },
        defaults: {
            anchor: AnchorLocations.Center,
            endpointStyle: { fill: "gray" },
            endpointHoverStyle: { fill: "#FF6600" }
        },
        refreshLayoutOnEdgeConnect:true,
        elementsDraggable:false,
        plugins:[
            {
                type:MiniviewPlugin.type,
                options:{
                    container:miniviewElement
                }
            }
        ],
        storePositionsInModel:false            // by default this is true, and useful. We set it to false in this demonstration to ensure that each layout
                                               // is operating without any previous placement values (the Absolute layout, for instance would just use
                                               // values from the model which had been generated by a previous layout, so you'd see no difference).
    })

    //
    // use event delegation to attach event handlers to
    // remove buttons. This callback finds the related Node and
    // then tells the toolkit to delete it.
    //
    renderer.bindModelEvent<Node>(EVENT_TAP, ".delete", (event:Event, target:HTMLElement, info:ObjectInfo<Node>) => {
        const selection = toolkit.selectDescendants(info.obj, true)
        toolkit.transaction(function() {
            toolkit.remove(selection)
        })
    })

    //
    // use event delegation to attach event handlers to
    // add buttons. This callback adds an edge from the given node
    // to a newly created node, and then the layout is refreshed.
    //
    renderer.bindModelEvent<Node>(EVENT_TAP, ".add", (event:Event, target:HTMLElement, info:ObjectInfo<Node>) => {
        // get a random node.
        const n = randomNode("node")

        // start a transaction so that the new node and the edge to the existing node are wrapped into a single
        // unit of work, and can be undone/redone together.
        toolkit.transaction(() => {
            // add the node to the toolkit
            const newNode = toolkit.addNode(n);
            // and add an edge for it from the current node.
            toolkit.addEdge({source: info.obj, target: newNode})
        })
    })

    const pickLayout = (e:Event) => {
        const sel = e.target as HTMLSelectElement,
            opt = sel.options[sel.selectedIndex],
            id = opt.value,
            extra = opt.getAttribute("extra") || "",

            // paramKey = id + extra,
            // params = layoutParams[paramKey] || {},
            params = getParams(id, extra),

            lp = {
                type:id,
                options:params
            }

        document.getElementById("layout-picker").setAttribute("data-main", id)

        renderer.setLayout(lp)
        renderer.zoomToFit()

        document.querySelector(".config pre").innerHTML = JSON.stringify(lp, 2, 2)
        return {id, extra}
    }

    // change layout when user picks one from the drop down.
    renderer.on(layoutSelector, "change", (e:Event) => {
        const {id, extra} = pickLayout(e)
        populateOptions(id)
        const sel = document.querySelector(`[data-layout='${id}']`) as HTMLSelectElement
        if (sel) {
            sel.selectedIndex = 0
        }
    })

    renderer.on(layoutOptionsSelector, "change", (e:Event) => {
        const {id, extra} = pickLayout(e)

    })

    renderer.on(document.querySelector("#btnRegenerate"), EVENT_CLICK, () => {
        toolkit.clear()
        toolkit.load({
            data:randomHierarchy(3)
        })
    })

    renderer.on(document.querySelector("#btnRelayout"), EVENT_CLICK, () => {
        renderer.relayout()
    })

    SUPPORTED_LAYOUTS.forEach((sl:string) => {
        const o= document.createElement("option")
        o.value = sl
        o.innerHTML = sl
        layoutSelector.appendChild(o)
    })

    populateOptions("Hierarchy")
})
